from __future__ import annotations
from typing import TYPE_CHECKING
from llvmlite import ir
from ast_classes import FunctionFlag
from llvm_types import VOID, I8_POINTER, I32
import llvmlite.binding as llvm
from representations.types.base_type import Type
from representations.value import Value, VoidValue
from runtime.c_runtime import CRuntime
from runtime.rc_runtime import RCRuntime

if TYPE_CHECKING:
    from runtime.rc_runtime import RCRuntime
    from runtime.c_runtime import CRuntime
    from representations.field import Field
    from representations.value import Value

class UserType(Type):
    """
    Every class defined by a user is held under a ``UserType``. Although 
    at compile time they are all of the same Python class, they effectively
    behave as seperate types, because the generated code can be very different
    depending on the user (the programmer who is using the language)'s code.
    """

    def __init__(self, module: ir.Module, name: str, rc_runtime: RCRuntime) -> None:
        super().__init__(module)
        self._name = name
        self._llvm_type = self.module.context.get_identified_type(self.name)
        self.rc_runtime = rc_runtime
        
        #: Maps user-provided names to Fields. This can be for variables or functions.
        self.field_names: dict[str, Field] = {}

        #: Maps user-provided names to indices in the LLVM ``IdentifiedStructType``.
        self.field_indices: dict[str, int] = {}

        #: List of names of user-defined functions that cast another type to this.
        self.casters: list[str] = [] # list of names

        #: The destructor type is always void (byte*)
        self._destructor_type: ir.FunctionType = ir.FunctionType(VOID, [I8_POINTER])

        #: The destructor function generated by ``_generate_destructor``. It is 
        #: named [TypeName]__destructor.
        self._destructor_func: ir.Function = ir.Function(self.module, self._destructor_type, f"{name}__destructor")
        self._destructor_generated = False
    
    @property
    def llvm_type(self) -> ir.IdentifiedStructType:
        """
        The LLVM type is an ``IdentifiedStructType``, meaniing it is opaque, and can 
        be used before it's fully defined. In practice, the type is defined after all
        the members are fully generated, meaning this opaque usage only happens inside
        member functions and variables, and also only really exists under the hood.
        """

        return self._llvm_type

    @property
    def name(self) -> str:
        """
        This is the user-defined name of the class.
        """

        return self._name
    
    @property
    def needs_refcount(self) -> bool:
        """
        All user defined types are reference counted. In the future I plan to add support
        for stack allocated user defined types.
        """

        return True
    
    def add_field(self, name: str, field: Field) -> None:
        """
        Used when parsing the class' internals. Raises and error if the field already 
        exists in the ``field_names`` dictionary. Also adds the field to ``casters``
        if applicable.
        """

        if name in self.field_names:
            raise ValueError(f"Field '{name}' already exists.")
        
        self.field_names[name] = field

        field_list = [f.val_type.llvm_type for f in self.field_names.values()]
        self.field_indices[name] = len(field_list) - 1

        if FunctionFlag.CAST in field.flags:
            self.casters.append(name)
    
    def finalize(self) -> None:
        """
        Finalises the class definition. You should definetely not use ``add_field`` after 
        this.
        """

        field_list = [f.val_type.llvm_type for f in self.field_names.values()]
        self.llvm_type.set_body(*field_list)
    
    def get_field(self, name: str) -> Field:
        """
        Gets a field from the class. This method doesn't have proper error handling, so
        make sure to check if the class ``has_field`` before using this.
        """

        return self.field_names[name]
    
    def has_field(self, name: str) -> bool:
        """
        Checks if the name is in the ``field_names`` dictionary.
        """

        return name in self.field_names
    
    def castable_from(self, cast_from: Type) -> bool:
        """
        If the user has defined a cast function, then this will 
        check if the supplied type can be casted to this implicitly.
        """

        return cast_from.name in self.casters
    
    def generate_from(self, builder: ir.IRBuilder, cast_from: Value, rc_runtime: RCRuntime, c_runtime: CRuntime, target_data: llvm.TargetData) -> Value:
        """
        Calls the user's cast function. Make sure to check with 
        ``castable_from`` to prevent errors. This isn't C and we are
        not bitcasting!
        """
        
        assert self.castable_from(cast_from.val_type)
        out = self.call_static(builder, cast_from.val_type.name, [cast_from], rc_runtime, target_data)
        assert not isinstance(out, VoidValue)
        return out
    
    def get_destructor(self) -> ir.Function | None:
        """
        Generates a destructor for all member values.
        """

        if not self._destructor_generated:
            self._generate_destructor()
            self._destructor_generated = True
        return self._destructor_func

    def _generate_destructor(self) -> None:
        """
        This function does all the heavy lifting for destructor
        generation. It is only called once by the ``get_destructor``
        function once.
        """

        block = self._destructor_func.append_basic_block("entry")
        builder = ir.IRBuilder(block)

        raw_ptr = self._destructor_func.args[0]
        self_ptr = builder.bitcast(raw_ptr, self.llvm_type.as_pointer(), "self_ptr")

        for field_name, fld in self.field_names.items():
            field_type = fld.val_type
            if not field_type.needs_refcount:
                continue
            idx = self.field_indices[field_name]
            field_ptr = builder.gep(self_ptr, [I32(0), I32(idx)], name="field_ptr")
            field_value = builder.load(field_ptr, "field_value")
            field_raw = builder.bitcast(field_value, I8_POINTER, "field_raw")
            field_destructor = field_type.get_destructor()
            if field_destructor:
                destructor_ptr = field_destructor
            else:
                destructor_fn_ty = ir.FunctionType(VOID, [I8_POINTER])
                destructor_ptr = ir.Constant(destructor_fn_ty.as_pointer(), None)
            builder.call(self.rc_runtime.rc_release_func, [field_raw, destructor_ptr])
        
        builder.ret_void()


class FunctionType(Type):
    """
    Class for CBLang functions. A function is itself a type, although
    every different function has a different type, even if their signature
    is the same. Likewise for LLVM.

    If a function is a class member, it will always take an instance of 
    the class as its first argument internally. This is handled automatically
    by the compiler.
    """

    def __init__(self, module: ir.Module, name: str, args: list[Type], returns: Type, function: ir.Function) -> None:
        super().__init__(module)
        self._name = name
        self._llvm_type = ir.FunctionType(returns.llvm_type, ((arg.llvm_type.as_pointer() if arg.needs_refcount else arg.llvm_type) for arg in args)).as_pointer()
        self.returns = returns
        self.args = args
        self.function = function
    
    @property
    def llvm_type(self) -> ir.Type:
        """
        A function's LLVM type is ```ir.FunctionType(...).as_pointer()``, 
        where the specifics of the return type and arguments are defined 
        by the user.
        """

        return self._llvm_type

    @property
    def name(self) -> str:
        """
        This is the function's name, which may not be unique globally like
        a normal type, but is unique within its scope.
        """

        return self._name
    
    @property
    def needs_refcount(self) -> bool:
        """
        Functions are stored as function pointer pointers, which might sound
        weird. But they aren't reference counted because  because functions 
        are stored in a global scope even if they are members.
        """

        return False
    
    def add_field(self, name: str, field: Field) -> None:
        raise RuntimeError("Cannot add a field to a FunctionType.")
    
    def get_field(self, name: str) -> Field:
        raise RuntimeError("(currently) Cannot get a field from the FunctionType.")
    
    def has_field(self, name: str) -> bool:
        return False


class InternalType(Type):
    """
    For types inside other classes. Proxies all methods to the 
    ``internal_type``.
    """

    def __init__(self, module: ir.Module, internal_type: UserType) -> None:
        super().__init__(module)

        #: The type that this contains. Hopefully, ``InternalType``
        #: would act exactly the same as this type.
        self.internal_type: UserType = internal_type
    
    @property
    def llvm_type(self) -> ir.IdentifiedStructType:
        return self.internal_type.llvm_type

    @property
    def name(self) -> str:
        return self.internal_type.name
    
    @property
    def needs_refcount(self) -> bool:
        return self.internal_type.needs_refcount
    
    def add_field(self, name: str, field: Field) -> None:
        raise RuntimeError("Cannot add a field to the InternalType.")
    
    def get_field(self, name: str) -> Field:
        return self.internal_type.get_field(name)
    
    def has_field(self, name: str) -> bool:
        return self.internal_type.has_field(name)
    
    def castable_from(self, cast_from: Type) -> bool: 
        return self.internal_type.castable_from(cast_from)
    
    def generate_from(self, builder: ir.IRBuilder, cast_from: Value, rc_runtime: RCRuntime, c_runtime: CRuntime, target_data: llvm.TargetData) -> Value:
        return self.internal_type.generate_from(builder, cast_from, rc_runtime, c_runtime, target_data)
